# Generated by Django 3.0b1 on 2019-11-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, db_index=True, null=True, verbose_name='自定义URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='标题'),
        ),
    ]
