# Generated by Django 3.0b1 on 2019-11-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20191117_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='自定义URL'),
        ),
    ]
