# Generated by Django 3.0b1 on 2019-11-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20191117_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read_num',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
