# Generated by Django 3.0b1 on 2019-11-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_background_color', models.CharField(blank=True, max_length=32, null=True, verbose_name='头部背景色')),
                ('content_background_color', models.CharField(blank=True, max_length=32, null=True, verbose_name='头部内容色')),
                ('bottom_background_color', models.CharField(blank=True, max_length=32, null=True, verbose_name='底部内容色')),
                ('head_color', models.CharField(blank=True, max_length=32, null=True, verbose_name='头部字体颜色')),
                ('content_color', models.CharField(blank=True, max_length=32, null=True, verbose_name='内容字体颜色')),
            ],
            options={
                'verbose_name': '设置',
                'verbose_name_plural': '设置',
                'db_table': 'blog_site',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, verbose_name='创建时间')),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '标签表',
                'verbose_name_plural': '标签表',
                'db_table': 'blog_tag',
            },
        ),
        migrations.CreateModel(
            name='WhiteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='访问ip')),
                ('is_ban', models.BooleanField(blank=True, default=False, verbose_name='Ban')),
                ('access', models.IntegerField(blank=True, default=False, verbose_name='访问次数')),
                ('chang_time', models.DateField(auto_now_add=True, verbose_name='最后访问时间')),
            ],
        ),
    ]
