# Generated by Django 3.0b1 on 2019-11-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whitelist',
            old_name='chang_time',
            new_name='last_time',
        ),
    ]
