# Generated by Django 3.0b1 on 2019-11-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20191117_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='whitelist',
            name='last_time',
            field=models.DateField(auto_now=True, verbose_name='最后访问时间'),
        ),
    ]
