# Generated by Django 3.0b1 on 2019-11-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20191117_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelist',
            name='ip',
            field=models.GenericIPAddressField(db_index=True, verbose_name='访问ip'),
        ),
    ]
